import JSZip from 'jszip';

type Bounds={x:number;y:number;width:number;height:number};
type Frame={key:string;frameOffset?:{x:number;y:number};frame:Bounds;spriteSourceSize:Bounds;sourceSize:{w:number;h:number}};
type Meta={sourceSize:{w:number;h:number};animations:Record<string,{frames:Frame[]}>;[key:string]:unknown};
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s);
const nativeCreate=URL.createObjectURL.bind(URL), nativeRevoke=URL.revokeObjectURL.bind(URL), nativeClick=HTMLAnchorElement.prototype.click;
const blobs=new Map<string,Blob>(); let capture=false, bypass=false;
URL.createObjectURL=((value:Blob|MediaSource)=>{const u=nativeCreate(value);if(value instanceof Blob)blobs.set(u,value);return u;}) as typeof URL.createObjectURL;
URL.revokeObjectURL=((u:string)=>{blobs.delete(u);nativeRevoke(u);}) as typeof URL.revokeObjectURL;
function png(c:HTMLCanvasElement){return new Promise<Blob>((ok,no)=>c.toBlob(b=>b?ok(b):no(new Error('PNG导出失败')),'image/png'));}
async function canvas(blob:Blob){const bm=await createImageBitmap(blob),c=document.createElement('canvas');c.width=bm.width;c.height=bm.height;c.getContext('2d')!.drawImage(bm,0,0);bm.close();return c;}
function extrude(ctx:CanvasRenderingContext2D,src:HTMLCanvasElement,b:Bounds,x:number,y:number,e:number){if(!e)return;ctx.drawImage(src,b.x,b.y,b.width,1,x,y-e,b.width,e);ctx.drawImage(src,b.x,b.y+b.height-1,b.width,1,x,y+b.height,b.width,e);ctx.drawImage(src,b.x,b.y,1,b.height,x-e,y,e,b.height);ctx.drawImage(src,b.x+b.width-1,b.y,1,b.height,x+b.width,y,e,b.height);ctx.drawImage(src,b.x,b.y,1,1,x-e,y-e,e,e);ctx.drawImage(src,b.x+b.width-1,b.y,1,1,x+b.width,y-e,e,e);ctx.drawImage(src,b.x,b.y+b.height-1,1,1,x-e,y+b.height,e,e);ctx.drawImage(src,b.x+b.width-1,b.y+b.height-1,1,1,x+b.width,y+b.height,e,e);}
async function optimize(zip:JSZip,path:string){const j=zip.file(path),p=zip.file(path.replace(/sprite\.json$/,'sprite.trim.png'));if(!j||!p)return;const meta=JSON.parse(await j.async('text')) as Meta,src=await canvas(await p.async('blob')), entries=Object.values(meta.animations||{}).flatMap(a=>a.frames||[]);if(!entries.length)return;const padding=2,edge=1,border=padding+edge,max=1024;let x=0,y=0,row=0,w=1;const places=new Map<string,{x:number;y:number;old:Bounds}>();for(const f of entries){const cw=f.frame.width+border*2,ch=f.frame.height+border*2;if(x&&x+cw>max){x=0;y+=row;row=0;}places.set(f.key,{x:x+border,y:y+border,old:{...f.frame}});x+=cw;row=Math.max(row,ch);w=Math.max(w,x);}const out=document.createElement('canvas');out.width=w;out.height=Math.max(1,y+row);const ctx=out.getContext('2d')!;ctx.imageSmoothingEnabled=false;for(const f of entries){const q=places.get(f.key)!;ctx.drawImage(src,q.old.x,q.old.y,q.old.width,q.old.height,q.x,q.y,q.old.width,q.old.height);extrude(ctx,src,q.old,q.x,q.y,edge);f.frame={x:q.x,y:q.y,width:q.old.width,height:q.old.height};}
const acts=Object.entries(meta.animations||{}),cols=Math.max(1,...acts.map(([,a])=>a.frames.length)),prev=document.createElement('canvas');prev.width=meta.sourceSize.w*cols;prev.height=meta.sourceSize.h*Math.max(1,acts.length);const pc=prev.getContext('2d')!;pc.imageSmoothingEnabled=false;acts.forEach(([,a],r)=>a.frames.forEach((f,c)=>pc.drawImage(out,f.frame.x,f.frame.y,f.frame.width,f.frame.height,c*meta.sourceSize.w+f.spriteSourceSize.x,r*meta.sourceSize.h+f.spriteSourceSize.y,f.spriteSourceSize.width,f.spriteSourceSize.height)));
zip.file(path.replace(/sprite\.json$/,'sprite.trim.png'),await png(out));zip.file(path,JSON.stringify({...meta,atlasPadding:padding,edgeExtrusion:edge},null,2));zip.file(path.replace(/sprite\.json$/,'sprite.preview.png'),await png(prev));}
async function run(blob:Blob,name:string){const zip=await JSZip.loadAsync(blob),paths=Object.keys(zip.files).filter(p=>p.endsWith('/game/sprite.json'));for(const p of paths)await optimize(zip,p);const out=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});const a=document.createElement('a'),u=nativeCreate(out);a.href=u;a.download=name;bypass=true;nativeClick.call(a);bypass=false;setTimeout(()=>nativeRevoke(u),1500);}
HTMLAnchorElement.prototype.click=function(){if(!bypass&&capture&&this.download.endsWith('_staff_assets.zip')){const blob=blobs.get(this.href);capture=false;if(blob){void run(blob,this.download).catch(e=>alert(`Atlas优化失败：${e instanceof Error?e.message:String(e)}`));return;}}return nativeClick.call(this);};
function install(){const b=$('#exportBatch') as HTMLButtonElement|null;if(!b)return requestAnimationFrame(install);if(b.dataset.atlasV15)return;b.dataset.atlasV15='1';b.addEventListener('click',()=>{capture=true;setTimeout(()=>{capture=false;},120000);},true);}
install();
