import './cleanup-workbench-v18.css';

const q=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s);
const REC={tolerance:50,spillStrength:100,weakAlpha:50,edgeErode:3,binaryThreshold:200,manualTolerance:80};
const next=()=>new Promise<void>(r=>requestAnimationFrame(()=>r()));
function wait(){return new Promise<void>(r=>{const t=()=>q('#cleanFringe')&&q('#manualTolerance')&&q('#viewportPanToggle')&&q('#dualMatteOpen')?r():requestAnimationFrame(t);t();});}
function node(id:string){return q(`#${id}`)?.closest<HTMLElement>('label')||q(`#${id}`);}
function move(to:HTMLElement,n:HTMLElement|null|undefined,c?:string){if(!n)return;if(c)n.classList.add(c);to.appendChild(n);}
function icon(b:HTMLButtonElement|null,i:string,label:string,title=''){if(!b)return;b.innerHTML=`<span class="cleanup-button-icon">${i}</span><span>${label}</span>`;if(title)b.title=title;}
function set(id:string,v:number,event='change'){const el=q<HTMLInputElement>(`#${id}`);if(!el)return;el.value=String(v);el.dispatchEvent(new Event(event,{bubbles:true}));}
function applyRecommended(){set('tolerance',REC.tolerance,'input');set('spillStrength',REC.spillStrength);set('weakAlpha',REC.weakAlpha);set('edgeErode',REC.edgeErode);set('binaryThreshold',REC.binaryThreshold);const m=q<HTMLInputElement>('#manualTolerance');if(m)m.value=String(REC.manualTolerance);const n=q<HTMLInputElement>('#toleranceNumber');if(n)n.value=String(REC.tolerance);}
async function applyAll(){const sel=q<HTMLSelectElement>('#importClip');if(!sel)return;const old=sel.value;for(const o of Array.from(sel.options)){sel.value=o.value;sel.dispatchEvent(new Event('change',{bubbles:true}));applyRecommended();await next();}sel.value=old;sel.dispatchEvent(new Event('change',{bubbles:true}));applyRecommended();}
function card(id:string,i:string,t:string,s:string){const e=document.createElement('section');e.id=id;e.className='cleanup-card';e.innerHTML=`<header class="cleanup-card-head"><span class="cleanup-card-icon">${i}</span><div><b>${t}</b><small>${s}</small></div></header><div class="cleanup-card-body"></div>`;return e;}
function addToleranceNumber(){const r=q<HTMLInputElement>('#tolerance'),line=r?.closest<HTMLElement>('.range-line');if(!r||!line||q('#toleranceNumber'))return;const n=document.createElement('input');n.id='toleranceNumber';n.type='number';n.min='0';n.max='120';n.value=r.value;n.className='cleanup-range-number';line.appendChild(n);r.addEventListener('input',()=>n.value=r.value);n.addEventListener('change',()=>{const v=Math.max(0,Math.min(120,Number(n.value)||0));n.value=r.value=String(v);r.dispatchEvent(new Event('input',{bubbles:true}));});}
function install(){const clean=q('#cleanFringe'),section=clean?.closest<HTMLElement>('.section');if(!section||q('#cleanupWorkbenchV18'))return;const title=section.querySelector<HTMLElement>('.section-title');if(title?.firstChild)title.firstChild.textContent='04 / 抠图精修 ';
addToleranceNumber();const wb=document.createElement('div');wb.id='cleanupWorkbenchV18';wb.className='cleanup-workbench';title?.after(wb);
const cards=[card('cleanupBackgroundCard','◐','背景与取样','先告诉工具哪里是背景'),card('cleanupParamCard','⌁','算法参数','常用清理参数集中设置'),card('cleanupManualCard','✦','手工精修','选择工具，再处理局部'),card('cleanupPreviewCard','◎','预览检查','放大、移动并检查边缘'),card('cleanupActionCard','↯','应用处理','当前动作、整批或高精度去背')];
const nav=document.createElement('div');nav.className='cleanup-quick-nav';[['◐','背景'],['⌁','参数'],['✦','手工'],['◎','预览'],['↯','执行']].forEach((x,i)=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<span>${x[0]}</span><small>${x[1]}</small>`;b.onclick=()=>cards[i].scrollIntoView({behavior:'smooth',block:'nearest'});nav.appendChild(b);});wb.append(nav,...cards);
const bg=cards[0].querySelector<HTMLElement>('.cleanup-card-body')!;move(bg,q('[data-bg-preset="pixel"]')?.closest<HTMLElement>('.preset-row'),'cleanup-preset-strip');move(bg,node('removeBg'));move(bg,node('backgroundColor'));move(bg,q('#autoSample')?.parentElement,'cleanup-sample-strip');move(bg,q('#sampleWarning'));icon(q<HTMLButtonElement>('#autoSample'),'◫','四角自动');icon(q<HTMLButtonElement>('#setWhite'),'□','白色');icon(q<HTMLButtonElement>('#setBlack'),'■','黑色');icon(q<HTMLButtonElement>('#pickColor'),'⌖','取色');
const pb=cards[1].querySelector<HTMLElement>('.cleanup-card-body')!,grid=document.createElement('div');grid.className='cleanup-param-grid';pb.appendChild(grid);['tolerance','spillStrength','weakAlpha','edgeErode','binaryThreshold','featherRadius','closedThreshold'].forEach(id=>move(grid,node(id),'cleanup-param-field'));const ts=node('tolerance')?.querySelector('span');if(ts)ts.textContent='色差容差';['edgeOnly','protectInternal','spillRemoval','pixelEdge','binaryAlpha','edgeSmooth'].forEach(id=>move(pb,node(id),'cleanup-compact-check'));const reset=document.createElement('button');reset.id='cleanupRecommendedReset';reset.className='btn small cleanup-reset-button';reset.type='button';reset.innerHTML='<span class="cleanup-button-icon">↺</span><span>恢复推荐参数</span>';reset.title='色差50 / 溢色100 / 弱透明50 / 收缩3 / 二值200 / 手工80';reset.onclick=applyRecommended;pb.appendChild(reset);const read=document.createElement('div');read.className='cleanup-recommended-readout';read.innerHTML='<span>推荐基准</span><code>50 · 100 · 50 · 3 · 200</code>';pb.appendChild(read);
const mb=cards[2].querySelector<HTMLElement>('.cleanup-card-body')!,manual=q<HTMLElement>('.manual-cleanup-controls');move(mb,manual);manual?.querySelector('.subhead')?.remove();manual?.querySelector('.preset-row')?.classList.add('cleanup-tool-strip');icon(manual?.querySelector('[data-manual-tool="connected-delete"]')||null,'⌁','连通删除');icon(manual?.querySelector('[data-manual-tool="magic-wand"]')||null,'✦','魔棒');icon(manual?.querySelector('[data-manual-tool="eraser"]')||null,'▱','橡皮擦');icon(q('#deleteMagicSelection'),'⌫','删除选区');icon(q('#clearMagicSelection'),'×','取消选区');icon(q('#resetManualCleanup'),'↺','清除本帧');manual?.querySelectorAll<HTMLElement>('.row').forEach(r=>r.classList.add('cleanup-manual-row'));
const vb=cards[3].querySelector<HTMLElement>('.cleanup-card-body')!;move(vb,node('previewMode'));move(vb,node('edgeInspection'),'cleanup-compact-check');move(vb,q('#viewportPanToggle')?.parentElement,'cleanup-pan-row');move(vb,q('#viewportPanStatus'));move(vb,node('exportDebug'),'cleanup-compact-check');icon(q('#viewportPanToggle'),'✋','拖动画布：开');icon(q('#viewportPanReset'),'◎','回到中心');
const ab=cards[4].querySelector<HTMLElement>('.cleanup-card-body')!,ag=document.createElement('div');ag.className='cleanup-actions-grid';ab.appendChild(ag);move(ag,q('#cleanFringe'),'cleanup-action-primary');move(ag,q('#applyBgAction'));move(ag,q('#applyBgBatch'));move(ag,q('#dualMatteOpen'),'cleanup-action-wide');icon(q('#cleanFringe'),'✦','一键清理边缘');icon(q('#applyBgAction'),'✓','当前动作');icon(q('#applyBgBatch'),'▦','整批应用');icon(q('#dualMatteOpen'),'◒','双背景高精度去背');
q('[data-bg-preset="pixel"]')?.addEventListener('click',()=>setTimeout(applyRecommended,0));q('#newBatch')?.addEventListener('click',()=>setTimeout(()=>void applyAll(),0));void applyAll();}
wait().then(install);
