import JSZip from 'jszip';
import './style.css';

type ClipId = 'idle' | 'walk_down' | 'walk_up' | 'walk_left' | 'walk_right' | 'typing' | 'celebrate' | 'tired';
type Anchor = 'feet' | 'seat';
type Bounds = { x: number; y: number; width: number; height: number };
type Region = { id: string; x: number; y: number; w: number; h: number; locked: boolean };
type ResizeHandle = 'nw' | 'n' | 'ne' | 'e' | 'se' | 's' | 'sw' | 'w';
type SliceInteraction = { mode: 'create' | 'move' | 'resize'; start: { x: number; y: number }; index: number; original?: Region; handle?: ResizeHandle };
type Point = { x: number; y: number };
type Frame = { canvas: HTMLCanvasElement; raw: HTMLCanvasElement; bbox: Bounds | null; partialAlpha: number; source: string; frameOffset: Point; sliceRect: Region };
type RawFrame = { canvas: HTMLCanvasElement; source: string };
type ClipSpec = { id: ClipId; label: string; fps: number; loop: boolean; recommended: number; anchor: Anchor };
type ClipConfig = { offset: Point; sourcePivot: Point | null };
type CharacterConfig = { canonicalScale: number; standingPivot: Point; seatPivot: Point; referenceAction: ClipId };
type Slot = { index: number; visualId: string; clips: Record<ClipId, Frame[]>; clipConfig: Record<ClipId, ClipConfig>; config: CharacterConfig };

const SLOT_COUNT = 18;
const specs: ClipSpec[] = [
  { id: 'idle', label: 'Idle 待机', fps: 6, loop: true, recommended: 5, anchor: 'feet' },
  { id: 'walk_down', label: 'Walk Down', fps: 8, loop: true, recommended: 7, anchor: 'feet' },
  { id: 'walk_up', label: 'Walk Up', fps: 8, loop: true, recommended: 7, anchor: 'feet' },
  { id: 'walk_left', label: 'Walk Left', fps: 8, loop: true, recommended: 7, anchor: 'feet' },
  { id: 'walk_right', label: 'Walk Right（可选）', fps: 8, loop: true, recommended: 7, anchor: 'feet' },
  { id: 'typing', label: 'Typing 打字', fps: 8, loop: true, recommended: 7, anchor: 'seat' },
  { id: 'celebrate', label: 'Celebrate 庆祝', fps: 10, loop: false, recommended: 8, anchor: 'feet' },
  { id: 'tired', label: 'Tired 疲劳', fps: 5, loop: true, recommended: 5, anchor: 'feet' },
];
const emptyClips = () => Object.fromEntries(specs.map(s => [s.id, [] as Frame[]])) as unknown as Record<ClipId, Frame[]>;
const emptyClipConfig = () => Object.fromEntries(specs.map(s => [s.id, { offset: { x: 0, y: 0 }, sourcePivot: null }])) as Record<ClipId, ClipConfig>;
const emptyRawFrames = () => Object.fromEntries(specs.map(s => [s.id, [] as RawFrame[]])) as unknown as Record<ClipId, RawFrame[]>;
const defaultCharacterConfig = (): CharacterConfig => ({ canonicalScale: 0, standingPivot: { x: 48, y: 106 }, seatPivot: { x: 48, y: 87 }, referenceAction: 'idle' });
const slots: Slot[] = Array.from({ length: SLOT_COUNT }, (_, index) => ({ index, visualId: `staff_visual_${String(index + 1).padStart(4, '0')}`, clips: emptyClips(), clipConfig: emptyClipConfig(), config: defaultCharacterConfig() }));
const rawFrames = emptyRawFrames();
const gridRegions = (cols = 6, rows = 3): Region[] => Array.from({ length: SLOT_COUNT }, (_, i) => ({ id: `character_${String(i + 1).padStart(2, '0')}`, x: i % cols / cols, y: Math.floor(i / cols) / rows, w: 1 / cols, h: 1 / rows, locked: false }));
const cloneRegions = (items: Region[]) => items.map(item => ({ ...item }));
const state = { slot: 0, clip: 'idle' as ClipId, frame: 0, view: 'batch' as 'batch' | 'character', playing: false, tick: 0, source: null as HTMLCanvasElement | null, sourceName: '', baseRegions: gridRegions(), actionOverrides: {} as Partial<Record<ClipId, Region[]>>, selectedSlice: 0, interaction: null as SliceInteraction | null, showBounds: true, showAnchor: true, onion: true, onionOpacity: .28, rawView: false };

const app = document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML = `
<main class="shell">
 <header class="topbar">
  <div class="brand"><div class="brand-mark">游</div><strong>员工 Sprite 工厂</strong><small>Trim · Pivot · Cross-action v1.4</small></div>
  <div class="hint">18 Slot · 外部 AI 素材后处理 · 不判断身份</div>
  <div class="top-actions"><button class="btn ghost" id="styleGuide">角色生产规范</button><button class="btn ghost" id="newBatch">新建批次</button><label class="btn ghost">打开批次<input hidden id="openBatch" type="file" accept="application/json,.json"></label><button class="btn" id="saveBatch">保存批次</button><button class="btn primary" id="exportBatch">导出 18 人 ZIP</button></div>
 </header>
 <section class="workspace">
  <aside class="sidebar">
   <div class="section"><div class="section-title">01 / Batch</div><label class="field"><span>Batch ID</span><input id="batchId" value="batch_001"></label><label class="field"><span>Visual ID 起始编号</span><input id="visualStart" type="number" min="1" value="1"></label><label class="field"><span>Asset Note</span><textarea id="assetNote" placeholder="人工备注，不进入游戏逻辑"></textarea></label></div>
   <div class="section"><div class="section-title">02 / Slice Tool <span id="sliceCount">18 / 18</span></div><div class="slice-scope" id="sliceScope">基础批次模板</div><p class="hint">Raw Slice View 中点击选中；拖动切片；拖八个控制点缩放。</p><div class="quad" id="sliceNumbers"><label class="field"><span>X px</span><input id="sliceX" type="number"></label><label class="field"><span>Y px</span><input id="sliceY" type="number"></label><label class="field"><span>W px</span><input id="sliceW" type="number" min="1"></label><label class="field"><span>H px</span><input id="sliceH" type="number" min="1"></label></div><button class="btn primary" id="applySlices" style="width:100%;margin:8px 0">应用切片到当前动作</button><div class="slice-tools"><button class="btn small" id="resetGrid">重置 6×3</button><button class="btn small" id="addSlice">新建切片</button><button class="btn small" id="deleteSlice">删除切片</button><button class="btn small" id="toggleLock">锁定 / 解锁</button></div><div class="row" style="margin-top:8px"><button class="btn small" id="createOverride">为当前动作建 Override</button><button class="btn small" id="clearOverride">移除 Override</button></div><div class="row" style="margin-top:8px"><button class="btn small" id="saveLayout">保存批次模板</button><label class="btn small" style="text-align:center">加载批次模板<input hidden id="loadLayout" type="file" accept="application/json,.json"></label></div></div>
   <div class="section"><div class="section-title">03 / Video & Image Import</div><label class="field"><span>动作类型</span><select id="importClip">${specs.map(s => `<option value="${s.id}">${s.label}</option>`).join('')}</select></label><div class="row"><label class="field"><span>开始秒</span><input id="startTime" type="number" min="0" step=".1" value="0"></label><label class="field"><span>结束秒（0=结尾）</span><input id="endTime" type="number" min="0" step=".1" value="0"></label></div><label class="field"><span>拆帧 FPS</span><input id="sampleFps" type="number" min="1" max="30" value="6"></label><label class="upload btn primary">导入视频 / 图片<input id="mediaInput" type="file" accept="video/mp4,video/webm,image/png,image/gif,image/webp" multiple></label><p class="hint">裁切始终使用该动作当前生效的 Slice Rect；有 Override 时优先使用 Override。</p></div>
   <div class="section"><div class="section-title">04 / Background Removal</div><label class="check"><input id="removeBg" type="checkbox" checked> 四角自动取色</label><label class="field"><span>Color Tolerance</span><div class="range-line"><input id="tolerance" type="range" min="0" max="120" value="28"><output id="toleranceOut">28</output></div></label><label class="check"><input id="edgeOnly" type="checkbox" checked> Edge Connected Only</label><label class="check"><input id="pixelEdge" type="checkbox" checked> Pixel Edge 0 / 255</label></div>
   <div class="section"><div class="section-title">05 / Source Canvas</div><label class="field"><span>Canvas Preset</span><select id="canvasPreset"><option value="96x112">96 × 112（默认）</option><option value="80x96">80 × 96</option><option value="custom">自定义</option></select></label><div class="row"><label class="field"><span>Width</span><input id="frameWidth" type="number" min="16" max="512" value="96"></label><label class="field"><span>Height</span><input id="frameHeight" type="number" min="16" max="512" value="112"></label></div><p class="hint">最终游戏坐标固定在 Source Canvas；Slice Rect 只负责从输入素材找人。</p></div>
  </aside>
  <div class="stage" id="stage"><div class="stage-tools"><button class="btn small active-view" data-view="batch">Raw Slice View</button><button class="btn small" data-view="character">Canonical Canvas View</button><button class="btn small" data-bg="checker">透明</button><button class="btn small" data-bg="office">办公室</button><button class="btn small" data-bg="black">黑</button></div><div class="frame-readout" id="frameReadout">等待导入 18 人素材</div><div class="canvas-wrap"><canvas id="preview" width="720" height="480"></canvas><div class="empty-state" id="empty"><b>导入一批 18 人动作素材</b>推荐 6 列 × 3 行；角色保持固定位置、不互相遮挡</div></div></div>
  <aside class="sidebar right"><div class="section"><div class="section-title">Character Slots <span id="slotSummary">0 / 18</span></div><div class="slot-grid" id="slotGrid"></div></div><div class="section"><div class="section-title">Selected Slot</div><div id="slotDetails"></div><button class="btn small" id="mirrorRight" style="width:100%;margin-top:10px">用 Walk Left 镜像生成 Right</button></div><div class="section"><div class="section-title">Canonical & Pivot</div><label class="field"><span>Canonical Scale（0=未建立）</span><input id="canonicalScale" type="number" min="0" step="0.001"></label><button class="btn primary small" id="establishBaseline" style="width:100%;margin-top:8px">从当前动作建立角色基准</button><div class="quad"><label class="field"><span>Stand X</span><input id="standX" type="number"></label><label class="field"><span>Stand Y</span><input id="standY" type="number"></label><label class="field"><span>Seat X</span><input id="seatX" type="number"></label><label class="field"><span>Seat Y</span><input id="seatY" type="number"></label></div><label class="field"><span>参考动作</span><select id="referenceAction">${specs.map(s => `<option value="${s.id}">${s.label}</option>`).join('')}</select></label></div><div class="section"><div class="section-title">Cross-action Align</div><div class="row"><label class="field"><span>Clip Offset X</span><input id="clipOffsetX" type="number" step="1"></label><label class="field"><span>Clip Offset Y</span><input id="clipOffsetY" type="number" step="1"></label></div><label class="check"><input id="onion" type="checkbox" checked> Onion Skin 叠加参考动作</label><label class="field"><span>Onion Opacity</span><input id="onionOpacity" type="range" min="0" max="0.8" step="0.05" value="0.28"></label></div><div class="section"><div class="section-title">Asset QA</div><div class="qa-list" id="qaList"></div></div><div class="section"><label class="check"><input id="showBounds" type="checkbox" checked> Bounding Box</label><label class="check"><input id="showAnchor" type="checkbox" checked> Pivot</label></div></aside>
 </section>
  <footer class="timeline"><div class="transport"><div class="section-title">Frame Review / <span id="reviewName">Idle</span></div><div class="transport-row"><button class="btn" id="prev">◀</button><button class="btn primary" id="play">▶ 播放</button><button class="btn" id="next">▶</button><label class="field" style="margin:0 0 0 auto"><span>FPS</span><input id="fps" type="number" min="1" max="30" value="6" style="width:58px"></label></div><div class="transport-row" style="margin-top:8px"><label class="mini-field">Frame X <input id="frameOffsetX" type="number" value="0"></label><label class="mini-field">Frame Y <input id="frameOffsetY" type="number" value="0"></label></div><div class="transport-row" style="margin-top:8px"><button class="btn small" id="deleteFrame">删除坏帧</button><button class="btn small" id="duplicateFrame">复制</button><button class="btn small" id="flipFrame">镜像</button><button class="btn small" id="sampleFrames">推荐采样</button></div></div><div class="timeline-strip" id="timelineStrip"><span class="hint">导入素材后检查拆帧结果。</span></div></footer>
</main>
<dialog id="styleDialog"><form method="dialog" class="guide-card"><button class="btn small guide-close">关闭</button><h2>18 人匿名员工生产规范</h2><p>供外部 AI 使用；Sprite 工厂本身不调用生图或视频模型。</p><pre>adult pixel game employee or creature,
orthographic 3/4 top-down view,
warm cozy management-game pixel art,
compact proportions, head-to-body ratio 1:3.2–1:3.6,
consistent camera angle, scale, lighting and pixel density,
full body visible, feet visible, clear silhouette,
18 subjects in stable non-overlapping positions,
allow safe margins around every subject; positions need not fill the canvas,
transparent or flat removable background</pre><h3>允许的角色范围</h3><p>正常成年人、狐狸耳、猫耳、兔耳、兽人、人外、异形、外星人、天使、恶魔、植物生命、机械生命、克苏鲁式原创奇异生物等均可。保持成年气质、统一比例和游戏内可读轮廓。</p><p class="hint">避免复制现有游戏角色；Typing 素材不要包含桌椅、电脑和键盘。</p></form></dialog>`;

const $ = <T extends HTMLElement>(q: string) => document.querySelector<T>(q)!;
const preview = $('#preview') as HTMLCanvasElement;
const previewCtx = preview.getContext('2d')!;
previewCtx.imageSmoothingEnabled = false;
const size = () => ({ w: Math.max(16, Number(($('#frameWidth') as HTMLInputElement).value)), h: Math.max(16, Number(($('#frameHeight') as HTMLInputElement).value)) });
const slot = () => slots[state.slot];
const frames = () => slot().clips[state.clip];
const spec = () => specs.find(s => s.id === state.clip)!;
const clipConfig = () => slot().clipConfig[state.clip];
const pivotFor = (s = slot(), clip = spec()) => clip.anchor === 'seat' ? s.config.seatPivot : s.config.standingPivot;

function updateIds() { const start = Math.max(1, Number(($('#visualStart') as HTMLInputElement).value)); slots.forEach((s, i) => s.visualId = `staff_visual_${String(start + i).padStart(4, '0')}`); renderSlots(); }
function regionsFor(action: ClipId): Region[] { return state.actionOverrides[action] ?? state.baseRegions; }
function editableRegions(): Region[] { return regionsFor(state.clip); }
function normalizeRegion(region: Region): Region { const min = .005; region.w = Math.max(min, Math.min(1, region.w)); region.h = Math.max(min, Math.min(1, region.h)); region.x = Math.max(0, Math.min(1 - region.w, region.x)); region.y = Math.max(0, Math.min(1 - region.h, region.y)); return region; }
function renumberRegions(items: Region[]) { items.forEach((item, i) => item.id = `character_${String(i + 1).padStart(2, '0')}`); }
function renderSliceStatus() { const items = editableRegions(), override = Boolean(state.actionOverrides[state.clip]), rawCount = rawFrames[state.clip].length; $('#sliceCount').textContent = `${items.length} / ${SLOT_COUNT}`; $('#sliceScope').innerHTML = `${override ? `<b>${state.clip}</b> 动作 Override` : '基础批次模板（所有无 Override 动作共用）'}<small>${rawCount ? ` · 已保留 ${rawCount} 个原始帧` : ' · 尚无可重裁原始帧'}</small>`; $('#toggleLock').textContent = items[state.selectedSlice]?.locked ? '解锁切片' : '锁定切片'; ($('#createOverride') as HTMLButtonElement).disabled = override; ($('#clearOverride') as HTMLButtonElement).disabled = !override; ($('#applySlices') as HTMLButtonElement).disabled = !rawCount || items.length !== SLOT_COUNT; syncSliceNumbers(); }
function renderAll() { renderSlots(); renderDetails(); renderSliceStatus(); syncAlignmentControls(); renderTimeline(); renderPreview(); renderQa(); }

function renderSlots() { const used = slots.filter(s => Object.values(s.clips).some(f => f.length)).length; $('#slotSummary').textContent = `${used} / ${SLOT_COUNT}`; $('#slotGrid').innerHTML = slots.map(s => { const actions = Object.values(s.clips).filter(f => f.length).length; return `<button class="slot-chip ${s.index === state.slot ? 'active' : ''} ${actions ? 'filled' : ''}" data-slot="${s.index}" title="${s.visualId}"><b>${String(s.index + 1).padStart(2, '0')}</b><small>${actions}/8</small></button>`; }).join(''); document.querySelectorAll<HTMLElement>('[data-slot]').forEach(el => el.onclick = () => { state.slot = Number(el.dataset.slot); state.selectedSlice = state.slot; state.frame = 0; state.view = 'character'; setViewButtons(); renderAll(); }); }
function renderDetails() { const s = slot(); $('#slotDetails').innerHTML = `<div class="visual-id mono">${s.visualId}</div><div class="action-matrix">${specs.map(c => `<button class="action-row ${c.id === state.clip ? 'active' : ''}" data-action="${c.id}"><span>${s.clips[c.id].length ? '✓' : '○'}</span><b>${c.id}</b><small>${s.clips[c.id].length} 帧</small></button>`).join('')}</div>`; document.querySelectorAll<HTMLElement>('[data-action]').forEach(el => el.onclick = () => selectClip(el.dataset.action as ClipId)); }
function selectClip(id: ClipId) { state.clip = id; state.frame = 0; ($('#importClip') as HTMLSelectElement).value = id; ($('#fps') as HTMLInputElement).value = String(spec().fps); $('#reviewName').textContent = spec().label; renderAll(); }
function setViewButtons() { document.querySelectorAll<HTMLElement>('[data-view]').forEach(el => el.classList.toggle('active-view', el.dataset.view === state.view)); }
function syncSliceNumbers() { const r = editableRegions()[state.selectedSlice], source = state.source; const values = r && source ? [r.x * source.width, r.y * source.height, r.w * source.width, r.h * source.height] : [0, 0, 0, 0]; ['sliceX', 'sliceY', 'sliceW', 'sliceH'].forEach((id, i) => { const input = $(`#${id}`) as HTMLInputElement; input.value = String(Math.round(values[i])); input.disabled = !r || !source || r.locked; }); }
function syncAlignmentControls() { const s = slot(), cfg = clipConfig(), f = frames()[state.frame]; ($('#canonicalScale') as HTMLInputElement).value = s.config.canonicalScale ? s.config.canonicalScale.toFixed(4) : '0'; ($('#standX') as HTMLInputElement).value = String(s.config.standingPivot.x); ($('#standY') as HTMLInputElement).value = String(s.config.standingPivot.y); ($('#seatX') as HTMLInputElement).value = String(s.config.seatPivot.x); ($('#seatY') as HTMLInputElement).value = String(s.config.seatPivot.y); ($('#referenceAction') as HTMLSelectElement).value = s.config.referenceAction; ($('#clipOffsetX') as HTMLInputElement).value = String(cfg.offset.x); ($('#clipOffsetY') as HTMLInputElement).value = String(cfg.offset.y); ($('#frameOffsetX') as HTMLInputElement).value = String(f?.frameOffset.x ?? 0); ($('#frameOffsetY') as HTMLInputElement).value = String(f?.frameOffset.y ?? 0); }

function renderPreview() { previewCtx.clearRect(0, 0, preview.width, preview.height); if (state.view === 'batch') renderBatch(); else renderCharacter(); }
function renderBatch() { if (!state.source) { $('#empty').style.display = 'block'; $('#empty').innerHTML = '<b>导入一批 18 人动作素材</b>随后可像 Photoshop Slice Tool 一样调整每个裁切区域'; return; } $('#empty').style.display = 'none'; const transform = sourceTransform(), items = editableRegions(); previewCtx.drawImage(state.source, transform.ox, transform.oy, transform.dw, transform.dh); items.forEach((r, i) => { const x = transform.ox + r.x * transform.dw, y = transform.oy + r.y * transform.dh, w = r.w * transform.dw, h = r.h * transform.dh, selected = i === state.selectedSlice; previewCtx.fillStyle = selected ? '#78d29418' : '#f0bf6710'; previewCtx.fillRect(x, y, w, h); previewCtx.strokeStyle = r.locked ? '#83908a' : selected ? '#78d294' : '#f0bf67'; previewCtx.lineWidth = selected ? 3 : 1; previewCtx.strokeRect(x, y, w, h); previewCtx.fillStyle = r.locked ? '#4d5751ee' : '#101510dd'; previewCtx.fillRect(x + 3, y + 3, 34, 18); previewCtx.fillStyle = '#efe9d8'; previewCtx.font = '11px monospace'; previewCtx.fillText(`${String(i + 1).padStart(2, '0')}${r.locked ? 'L' : ''}`, x + 6, y + 16); if (selected && !r.locked) drawHandles(x, y, w, h); }); const override = state.actionOverrides[state.clip] ? `${state.clip} Override` : '基础模板'; $('#frameReadout').textContent = `${state.sourceName} · ${items.length}/18 Slice · ${override}`; }
function sourceTransform() { if (!state.source) return { ox: 0, oy: 0, dw: preview.width, dh: preview.height }; const scale = Math.min(preview.width / state.source.width, preview.height / state.source.height), dw = state.source.width * scale, dh = state.source.height * scale; return { ox: (preview.width - dw) / 2, oy: (preview.height - dh) / 2, dw, dh }; }
function drawHandles(x: number, y: number, w: number, h: number) { const points = [[x, y], [x + w / 2, y], [x + w, y], [x + w, y + h / 2], [x + w, y + h], [x + w / 2, y + h], [x, y + h], [x, y + h / 2]]; previewCtx.fillStyle = '#dfffea'; previewCtx.strokeStyle = '#183820'; points.forEach(([px, py]) => { previewCtx.fillRect(px - 4, py - 4, 8, 8); previewCtx.strokeRect(px - 4, py - 4, 8, 8); }); }
function sourcePoint(event: PointerEvent) { const rect = preview.getBoundingClientRect(), px = (event.clientX - rect.left) * preview.width / rect.width, py = (event.clientY - rect.top) * preview.height / rect.height, t = sourceTransform(); return { x: (px - t.ox) / t.dw, y: (py - t.oy) / t.dh }; }
function handleAt(point: { x: number; y: number }, region: Region): ResizeHandle | null { const t = sourceTransform(), radiusX = 8 / t.dw, radiusY = 8 / t.dh, handles: [ResizeHandle, number, number][] = [['nw', region.x, region.y], ['n', region.x + region.w / 2, region.y], ['ne', region.x + region.w, region.y], ['e', region.x + region.w, region.y + region.h / 2], ['se', region.x + region.w, region.y + region.h], ['s', region.x + region.w / 2, region.y + region.h], ['sw', region.x, region.y + region.h], ['w', region.x, region.y + region.h / 2]]; return handles.find(([, x, y]) => Math.abs(point.x - x) <= radiusX && Math.abs(point.y - y) <= radiusY)?.[0] ?? null; }
function beginSliceInteraction(event: PointerEvent) { if (state.view !== 'batch' || !state.source) return; const point = sourcePoint(event); if (point.x < 0 || point.x > 1 || point.y < 0 || point.y > 1) return; const items = editableRegions(), selected = items[state.selectedSlice], selectedHandle = selected && !selected.locked ? handleAt(point, selected) : null; if (selectedHandle && selected) { state.slot = state.selectedSlice; state.interaction = { mode: 'resize', start: point, index: state.selectedSlice, original: { ...selected }, handle: selectedHandle }; } else { let hit = -1; for (let i = items.length - 1; i >= 0; i--) { const r = items[i]; if (point.x >= r.x && point.x <= r.x + r.w && point.y >= r.y && point.y <= r.y + r.h) { hit = i; break; } } if (hit >= 0) { state.selectedSlice = hit; state.slot = hit; const item = items[hit]; if (!item.locked) state.interaction = { mode: 'move', start: point, index: hit, original: { ...item } }; } else if (items.length < SLOT_COUNT) { const item: Region = { id: `character_${String(items.length + 1).padStart(2, '0')}`, x: point.x, y: point.y, w: .005, h: .005, locked: false }; items.push(item); state.selectedSlice = items.length - 1; state.slot = state.selectedSlice; state.interaction = { mode: 'create', start: point, index: state.selectedSlice }; } } preview.setPointerCapture(event.pointerId); renderAll(); }
function updateSliceInteraction(event: PointerEvent) { const action = state.interaction; if (!action) return; const items = editableRegions(), item = items[action.index], point = sourcePoint(event); if (!item) return; if (action.mode === 'create') { item.x = Math.min(action.start.x, point.x); item.y = Math.min(action.start.y, point.y); item.w = Math.abs(point.x - action.start.x); item.h = Math.abs(point.y - action.start.y); normalizeRegion(item); } else if (action.mode === 'move' && action.original) { item.x = action.original.x + point.x - action.start.x; item.y = action.original.y + point.y - action.start.y; normalizeRegion(item); } else if (action.mode === 'resize' && action.original && action.handle) { const original = action.original, dx = point.x - action.start.x, dy = point.y - action.start.y; let left = original.x, top = original.y, right = original.x + original.w, bottom = original.y + original.h; if (action.handle.includes('w')) left += dx; if (action.handle.includes('e')) right += dx; if (action.handle.includes('n')) top += dy; if (action.handle.includes('s')) bottom += dy; if (right < left) [left, right] = [right, left]; if (bottom < top) [top, bottom] = [bottom, top]; item.x = left; item.y = top; item.w = right - left; item.h = bottom - top; normalizeRegion(item); } renderSliceStatus(); renderPreview(); }
function endSliceInteraction(event: PointerEvent) { if (!state.interaction) return; const items = editableRegions(), item = items[state.interaction.index]; if (state.interaction.mode === 'create' && item && (item.w < .01 || item.h < .01)) { items.splice(state.interaction.index, 1); renumberRegions(items); state.selectedSlice = Math.max(0, items.length - 1); } state.interaction = null; if (preview.hasPointerCapture(event.pointerId)) preview.releasePointerCapture(event.pointerId); renderAll(); }
function renderCharacter() { const f = frames()[state.frame]; if (!f) { $('#empty').style.display = 'block'; $('#empty').innerHTML = `<b>${slot().visualId}</b>${state.clip} 尚未导入`; $('#frameReadout').textContent = `${slot().visualId} · ${state.clip} · 0 帧`; return; } $('#empty').style.display = 'none'; const s = size(), zoom = Math.min((preview.width - 80) / s.w, (preview.height - 50) / s.h), dw = s.w * zoom, dh = s.h * zoom, ox = (preview.width - dw) / 2, oy = (preview.height - dh) / 2; const reference = slot().clips[slot().config.referenceAction]; if (state.onion && slot().config.referenceAction !== state.clip && reference.length) { previewCtx.save(); previewCtx.globalAlpha = state.onionOpacity; previewCtx.drawImage(reference[Math.min(state.frame, reference.length - 1)].canvas, ox, oy, dw, dh); previewCtx.restore(); } previewCtx.drawImage(f.canvas, ox, oy, dw, dh); if (state.showBounds && f.bbox) { previewCtx.strokeStyle = '#f0bf67'; previewCtx.setLineDash([5, 3]); previewCtx.strokeRect(ox + f.bbox.x * zoom, oy + f.bbox.y * zoom, f.bbox.width * zoom, f.bbox.height * zoom); } if (state.showAnchor) { const pivot = pivotFor(); previewCtx.strokeStyle = spec().anchor === 'seat' ? '#72d5d0' : '#78d294'; previewCtx.setLineDash([]); previewCtx.beginPath(); previewCtx.moveTo(ox + (pivot.x - 8) * zoom, oy + pivot.y * zoom); previewCtx.lineTo(ox + (pivot.x + 8) * zoom, oy + pivot.y * zoom); previewCtx.moveTo(ox + pivot.x * zoom, oy + (pivot.y - 8) * zoom); previewCtx.lineTo(ox + pivot.x * zoom, oy + (pivot.y + 8) * zoom); previewCtx.stroke(); } $('#frameReadout').textContent = `${slot().visualId} · ${state.clip} · ${state.frame + 1}/${frames().length} · Scale ${slot().config.canonicalScale.toFixed(3)} · Clip (${clipConfig().offset.x}, ${clipConfig().offset.y})`; }
function renderTimeline() { const list = frames(); if (!list.length) { $('#timelineStrip').innerHTML = '<span class="hint">当前 Slot 的这个动作还没有拆帧。</span>'; return; } $('#timelineStrip').innerHTML = list.map((_, i) => `<div class="thumb ${i === state.frame ? 'active' : ''}" data-frame="${i}"><span class="thumb-index">${String(i + 1).padStart(2, '0')}</span><canvas></canvas></div>`).join(''); document.querySelectorAll<HTMLElement>('[data-frame]').forEach((el, i) => { const c = el.querySelector('canvas')!, s = size(); c.width = s.w; c.height = s.h; c.getContext('2d')!.drawImage(list[i].canvas, 0, 0); el.onclick = () => { state.frame = i; syncAlignmentControls(); renderTimeline(); renderPreview(); }; }); }
function renderQa() { const list = frames(), partial = list.reduce((n, f) => n + f.partialAlpha, 0), empty = list.filter(f => !f.bbox).length, boundary = list.filter(f => f.bbox && (f.bbox.x <= 0 || f.bbox.y <= 0 || f.bbox.x + f.bbox.width >= size().w || f.bbox.y + f.bbox.height >= size().h)).length, frameDrift = list.filter(f => f.frameOffset.x || f.frameOffset.y).length, referenceReady = Boolean(slot().config.canonicalScale); const q: [string, string, string][] = [['Canonical Scale', referenceReady ? slot().config.canonicalScale.toFixed(4) : '未建立', referenceReady ? 'green' : 'red'], ['Scale Drift', referenceReady ? '固定角色级 Scale' : '需要基准', referenceReady ? 'green' : 'red'], ['Pivot Drift', frameDrift ? `${frameDrift} 帧有 Override` : '无单帧偏移', frameDrift > Math.max(2, list.length * .25) ? 'yellow' : list.length ? 'green' : 'yellow'], ['Clip Boundary', boundary ? `${boundary} 帧触边` : '未触边', boundary ? 'red' : list.length ? 'green' : 'yellow'], ['Alpha Edge', partial ? `${partial} 半透明像素` : '0 / 255', partial ? 'yellow' : list.length ? 'green' : 'yellow'], ['Empty Frame', empty ? `${empty} 个空帧` : '未发现', empty ? 'red' : list.length ? 'green' : 'yellow']]; $('#qaList').innerHTML = q.map(([a, b, c]) => `<div class="qa-item ${c}"><span>${a}</span><span>${b}</span></div>`).join(''); }

async function importMedia(files: FileList) { const target = ($('#importClip') as HTMLSelectElement).value as ClipId; state.clip = target; for (const file of Array.from(files)) { if (file.type.startsWith('video/')) await importVideo(file, target); else await importImage(file, target); } state.view = 'batch'; state.frame = 0; setViewButtons(); renderAll(); }
async function importImage(file: File, target: ClipId) { const image = await createImageBitmap(file), source = document.createElement('canvas'); source.width = image.width; source.height = image.height; source.getContext('2d')!.drawImage(image, 0, 0); state.source = source; state.sourceName = file.name; assertEighteenSlices(target); rawFrames[target].push({ canvas: source, source: file.name }); splitFrame(source, target, file.name); }
async function importVideo(file: File, target: ClipId) { const video = document.createElement('video'), url = URL.createObjectURL(file); video.src = url; video.muted = true; await new Promise<void>((ok, fail) => { video.onloadedmetadata = () => ok(); video.onerror = () => fail(new Error(`无法读取 ${file.name}`)); }); const start = Math.max(0, Number(($('#startTime') as HTMLInputElement).value)), requestedEnd = Number(($('#endTime') as HTMLInputElement).value), end = requestedEnd > start ? Math.min(requestedEnd, video.duration) : video.duration, fps = Math.max(1, Number(($('#sampleFps') as HTMLInputElement).value)); assertEighteenSlices(target); let count = 0; for (let t = start; t <= end && count < 180; t += 1 / fps, count++) { await seek(video, Math.min(t, video.duration)); const source = document.createElement('canvas'); source.width = video.videoWidth; source.height = video.videoHeight; source.getContext('2d')!.drawImage(video, 0, 0); state.source = source; state.sourceName = `${file.name} @ ${t.toFixed(2)}s`; rawFrames[target].push({ canvas: source, source: file.name }); splitFrame(source, target, file.name); } URL.revokeObjectURL(url); }
function seek(video: HTMLVideoElement, time: number) { return new Promise<void>((ok, fail) => { video.onseeked = () => ok(); video.onerror = () => fail(new Error('视频定位失败')); video.currentTime = time; }); }
function assertEighteenSlices(target: ClipId) { const items = regionsFor(target); if (items.length !== SLOT_COUNT) throw new Error(`${target} 当前生效的 Slice Rect 为 ${items.length} 个，必须正好是 18 个才能拆帧。`); }
function splitFrame(source: HTMLCanvasElement, target: ClipId, sourceName: string) { const layout = regionsFor(target); assertEighteenSlices(target); layout.forEach((r, i) => { const sx = Math.round(r.x * source.width), sy = Math.round(r.y * source.height), sw = Math.max(1, Math.round(r.w * source.width)), sh = Math.max(1, Math.round(r.h * source.height)), raw = document.createElement('canvas'); raw.width = sw; raw.height = sh; raw.getContext('2d')!.drawImage(source, sx, sy, sw, sh, 0, 0, sw, sh); slots[i].clips[target].push(process(raw, sourceName, target, i, r)); }); }
function applySlicesToCurrentAction() { const target = state.clip, originals = rawFrames[target]; assertEighteenSlices(target); if (!originals.length) return alert('当前动作没有保留的原始拆帧。请重新导入一次该动作素材。'); slots.forEach(s => { s.clips[target] = []; s.clipConfig[target].sourcePivot = null; }); originals.forEach(raw => splitFrame(raw.canvas, target, raw.source)); state.slot = state.selectedSlice; state.frame = 0; state.view = 'character'; setViewButtons(); renderAll(); }

function process(raw: HTMLCanvasElement, source: string, target: ClipId, slotIndex: number, sliceRect: Region): Frame { if (($('#removeBg') as HTMLInputElement).checked) removeBackground(raw); const s = slots[slotIndex], clip = s.clipConfig[target], rawBounds = findBounds(raw.getContext('2d')!.getImageData(0, 0, raw.width, raw.height)); if (rawBounds && !s.config.canonicalScale) s.config.canonicalScale = Math.min((size().h - 12) / rawBounds.height, (size().w - 8) / rawBounds.width); if (rawBounds && !clip.sourcePivot) clip.sourcePivot = { x: rawBounds.x + rawBounds.width / 2, y: rawBounds.y + rawBounds.height }; const frame: Frame = { canvas: document.createElement('canvas'), raw, bbox: null, partialAlpha: 0, source, frameOffset: { x: 0, y: 0 }, sliceRect: { ...sliceRect } }; rebuildFrame(s, target, frame); return frame; }
function rebuildFrame(s: Slot, target: ClipId, frame: Frame) { const canvasSize = size(), out = document.createElement('canvas'); out.width = canvasSize.w; out.height = canvasSize.h; const c = out.getContext('2d', { willReadFrequently: true })!; c.imageSmoothingEnabled = false; const clip = s.clipConfig[target], action = specs.find(item => item.id === target)!, pivot = action.anchor === 'seat' ? s.config.seatPivot : s.config.standingPivot, sourcePivot = clip.sourcePivot ?? { x: frame.raw.width / 2, y: frame.raw.height }, scale = s.config.canonicalScale || 1, dx = Math.round(pivot.x + clip.offset.x + frame.frameOffset.x - sourcePivot.x * scale), dy = Math.round(pivot.y + clip.offset.y + frame.frameOffset.y - sourcePivot.y * scale); c.drawImage(frame.raw, dx, dy, Math.round(frame.raw.width * scale), Math.round(frame.raw.height * scale)); if (($('#pixelEdge') as HTMLInputElement).checked) quantize(c, canvasSize.w, canvasSize.h); const data = c.getImageData(0, 0, canvasSize.w, canvasSize.h); frame.canvas = out; frame.bbox = findBounds(data); frame.partialAlpha = 0; for (let i = 3; i < data.data.length; i += 4) if (data.data[i] > 0 && data.data[i] < 255) frame.partialAlpha++; }
function rebuildSlot(s = slot()) { specs.forEach(action => s.clips[action.id].forEach(frame => rebuildFrame(s, action.id, frame))); }
function removeBackground(canvas: HTMLCanvasElement) { const c = canvas.getContext('2d', { willReadFrequently: true })!, image = c.getImageData(0, 0, canvas.width, canvas.height), d = image.data, corners = [0, (canvas.width - 1) * 4, (canvas.height - 1) * canvas.width * 4, (canvas.width * canvas.height - 1) * 4], color = [0, 1, 2].map(ch => Math.round(corners.reduce((n, i) => n + d[i + ch], 0) / 4)), tolerance = Number(($('#tolerance') as HTMLInputElement).value), match = (i: number) => Math.max(Math.abs(d[i] - color[0]), Math.abs(d[i + 1] - color[1]), Math.abs(d[i + 2] - color[2])) <= tolerance; if (!($('#edgeOnly') as HTMLInputElement).checked) for (let i = 0; i < d.length; i += 4) { if (match(i)) d[i + 3] = 0; } else { const seen = new Uint8Array(canvas.width * canvas.height), queue: number[] = []; for (let x = 0; x < canvas.width; x++) queue.push(x, (canvas.height - 1) * canvas.width + x); for (let y = 1; y < canvas.height - 1; y++) queue.push(y * canvas.width, y * canvas.width + canvas.width - 1); let head = 0; while (head < queue.length) { const p = queue[head++]; if (seen[p]) continue; seen[p] = 1; if (!match(p * 4)) continue; d[p * 4 + 3] = 0; const x = p % canvas.width, y = Math.floor(p / canvas.width); if (x) queue.push(p - 1); if (x < canvas.width - 1) queue.push(p + 1); if (y) queue.push(p - canvas.width); if (y < canvas.height - 1) queue.push(p + canvas.width); } } c.putImageData(image, 0, 0); }
function quantize(c: CanvasRenderingContext2D, w: number, h: number) { const image = c.getImageData(0, 0, w, h); for (let i = 3; i < image.data.length; i += 4) image.data[i] = image.data[i] >= 128 ? 255 : 0; c.putImageData(image, 0, 0); }
function findBounds(image: ImageData): Bounds | null { let minX = image.width, minY = image.height, maxX = -1, maxY = -1; for (let y = 0; y < image.height; y++) for (let x = 0; x < image.width; x++) if (image.data[(y * image.width + x) * 4 + 3]) { minX = Math.min(minX, x); minY = Math.min(minY, y); maxX = Math.max(maxX, x); maxY = Math.max(maxY, y); } return maxX < 0 ? null : { x: minX, y: minY, width: maxX - minX + 1, height: maxY - minY + 1 }; }
function flip(source: HTMLCanvasElement) { const out = document.createElement('canvas'); out.width = source.width; out.height = source.height; const c = out.getContext('2d')!; c.translate(out.width, 0); c.scale(-1, 1); c.drawImage(source, 0, 0); return out; }

function metadata(s: Slot, packed: Record<string, { frame: Bounds; spriteSourceSize: Bounds; sourceSize: { w: number; h: number } }>) { const fs = size(), used = specs.filter(c => s.clips[c.id].length); return { schemaVersion: 2, visualId: s.visualId, sourceSize: { w: fs.w, h: fs.h }, canonicalScale: s.config.canonicalScale, standingPivot: s.config.standingPivot, seatPivot: s.config.seatPivot, referenceAction: s.config.referenceAction, animations: Object.fromEntries(used.map(c => [c.id, { fps: c.fps, loop: c.loop, anchor: c.anchor, clipOffset: s.clipConfig[c.id].offset, frames: s.clips[c.id].map((f, i) => ({ key: `${c.id}_${String(i).padStart(3, '0')}`, frameOffset: f.frameOffset, ...packed[`${c.id}_${i}`] })) }])) }; }
function canvasBlob(out: HTMLCanvasElement) { return new Promise<Blob>((ok, fail) => out.toBlob(b => b ? ok(b) : fail(new Error('PNG 导出失败')), 'image/png')); }
async function fullSheet(s: Slot) { const fs = size(), used = specs.filter(c => s.clips[c.id].length), cols = Math.max(1, ...used.map(c => s.clips[c.id].length)), out = document.createElement('canvas'); out.width = fs.w * cols; out.height = fs.h * Math.max(1, used.length); const c = out.getContext('2d')!; used.forEach((clip, row) => s.clips[clip.id].forEach((f, col) => c.drawImage(f.canvas, col * fs.w, row * fs.h))); return canvasBlob(out); }
async function trimmedSheet(s: Slot) { const fs = size(), entries = specs.flatMap(clip => s.clips[clip.id].map((frame, index) => ({ clip: clip.id, index, frame, bounds: frame.bbox ?? { x: 0, y: 0, width: 1, height: 1 } }))), maxWidth = 1024, gap = 1; let x = 0, y = 0, rowH = 0, width = 1; const placements: { entry: typeof entries[number]; x: number; y: number }[] = []; for (const entry of entries) { if (x && x + entry.bounds.width > maxWidth) { x = 0; y += rowH + gap; rowH = 0; } placements.push({ entry, x, y }); x += entry.bounds.width + gap; rowH = Math.max(rowH, entry.bounds.height); width = Math.max(width, x); } const out = document.createElement('canvas'); out.width = Math.max(1, width - gap); out.height = Math.max(1, y + rowH); const c = out.getContext('2d')!, packed: Record<string, { frame: Bounds; spriteSourceSize: Bounds; sourceSize: { w: number; h: number } }> = {}; placements.forEach(({ entry, x: px, y: py }) => { const b = entry.bounds; c.drawImage(entry.frame.canvas, b.x, b.y, b.width, b.height, px, py, b.width, b.height); packed[`${entry.clip}_${entry.index}`] = { frame: { x: px, y: py, width: b.width, height: b.height }, spriteSourceSize: { x: b.x, y: b.y, width: b.width, height: b.height }, sourceSize: { w: fs.w, h: fs.h } }; }); return { blob: await canvasBlob(out), packed }; }
async function exportBatch() { const zip = new JSZip(), batchId = ($('#batchId') as HTMLInputElement).value.trim() || 'batch_001', root = zip.folder(batchId)!; for (const s of slots) { if (!Object.values(s.clips).some(f => f.length)) continue; const folder = root.folder(s.visualId)!, game = folder.folder('game')!, debug = folder.folder('debug')!, packed = await trimmedSheet(s); game.file('sprite.trim.png', packed.blob); game.file('sprite.json', JSON.stringify(metadata(s, packed.packed), null, 2)); debug.file('canonical.full.png', await fullSheet(s)); debug.file('alignment.json', JSON.stringify({ config: s.config, clips: s.clipConfig, qa: 'Full canonical canvases retained for pivot and boundary inspection.' }, null, 2)); } download(await zip.generateAsync({ type: 'blob' }), `${batchId}_18_staff_assets.zip`); }
function download(blob: Blob, name: string) { const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }
function saveBatch() { const payload = { schemaVersion: 3, batchId: ($('#batchId') as HTMLInputElement).value, visualStart: Number(($('#visualStart') as HTMLInputElement).value), assetNote: ($('#assetNote') as HTMLTextAreaElement).value, sliceTemplate: state.baseRegions, actionSliceOverrides: state.actionOverrides, frame: size(), slots: slots.map(s => ({ visualId: s.visualId, config: s.config, clipConfig: s.clipConfig, clips: Object.fromEntries(specs.map(c => [c.id, s.clips[c.id].map(f => ({ canvas: f.canvas.toDataURL(), raw: f.raw.toDataURL(), frameOffset: f.frameOffset, sliceRect: f.sliceRect, source: f.source }))])) })) }; download(new Blob([JSON.stringify(payload)], { type: 'application/json' }), `${payload.batchId}.sprite-batch.json`); }
async function imageCanvas(url: string) { const image = new Image(); image.src = url; await image.decode(); const canvas = document.createElement('canvas'); canvas.width = image.width; canvas.height = image.height; canvas.getContext('2d')!.drawImage(image, 0, 0); return canvas; }
async function openBatch(file: File) { const data = JSON.parse(await file.text()); ($('#batchId') as HTMLInputElement).value = data.batchId || 'batch_001'; ($('#visualStart') as HTMLInputElement).value = String(data.visualStart || 1); ($('#assetNote') as HTMLTextAreaElement).value = data.assetNote || ''; state.baseRegions = normalizeLoadedRegions(data.sliceTemplate || data.customRegions || gridRegions()); state.actionOverrides = Object.fromEntries(Object.entries(data.actionSliceOverrides || {}).map(([key, value]) => [key, normalizeLoadedRegions(value as Region[])])) as Partial<Record<ClipId, Region[]>>; if (data.frame) { ($('#frameWidth') as HTMLInputElement).value = String(data.frame.w || 96); ($('#frameHeight') as HTMLInputElement).value = String(data.frame.h || 112); } for (let i = 0; i < SLOT_COUNT; i++) { const stored = data.slots?.[i]; slots[i].visualId = stored?.visualId || slots[i].visualId; slots[i].config = stored?.config || defaultCharacterConfig(); slots[i].clipConfig = stored?.clipConfig || emptyClipConfig(); for (const c of specs) { slots[i].clips[c.id] = []; for (const item of stored?.clips?.[c.id] || []) { if (typeof item === 'string') { const canvas = await imageCanvas(item); slots[i].clips[c.id].push({ canvas, raw: canvas, bbox: findBounds(canvas.getContext('2d')!.getImageData(0, 0, canvas.width, canvas.height)), partialAlpha: 0, source: file.name, frameOffset: { x: 0, y: 0 }, sliceRect: regionsFor(c.id)[i] }); } else { const canvas = await imageCanvas(item.canvas), raw = await imageCanvas(item.raw || item.canvas); slots[i].clips[c.id].push({ canvas, raw, bbox: findBounds(canvas.getContext('2d')!.getImageData(0, 0, canvas.width, canvas.height)), partialAlpha: 0, source: item.source || file.name, frameOffset: item.frameOffset || { x: 0, y: 0 }, sliceRect: item.sliceRect || regionsFor(c.id)[i] }); } } } } state.selectedSlice = 0; renderAll(); }
function clearRawFrames() { specs.forEach(s => rawFrames[s.id] = []); }
function normalizeLoadedRegions(items: Region[]) { return items.map((item, i) => normalizeRegion({ ...item, id: `character_${String(i + 1).padStart(2, '0')}`, locked: Boolean(item.locked) })); }
function reset() { if (slots.some(s => Object.values(s.clips).some(f => f.length)) && !confirm('清空当前 18 人批次？')) return; slots.forEach(s => { s.clips = emptyClips(); s.clipConfig = emptyClipConfig(); s.config = defaultCharacterConfig(); }); clearRawFrames(); state.source = null; state.baseRegions = gridRegions(); state.actionOverrides = {}; state.selectedSlice = 0; state.frame = 0; renderAll(); }
function saveLayout() { download(new Blob([JSON.stringify({ schemaVersion: 2, layoutId: ($('#batchId') as HTMLInputElement).value, slotCount: SLOT_COUNT, slices: state.baseRegions }, null, 2)], { type: 'application/json' }), `${($('#batchId') as HTMLInputElement).value}.slice-template.json`); }
async function loadLayout(file: File) { const data = JSON.parse(await file.text()), loaded = data.slices || data.slots; if (!Array.isArray(loaded) || loaded.length !== SLOT_COUNT) throw new Error('批次 Slice Template 必须正好包含 18 个切片'); state.baseRegions = normalizeLoadedRegions(loaded); state.selectedSlice = 0; renderAll(); }
function recommendedSample() { const list = frames(), target = spec().recommended; if (list.length <= target) return; slot().clips[state.clip] = Array.from({ length: target }, (_, i) => list[Math.round(i * (list.length - 1) / (target - 1))]); state.frame = 0; renderAll(); }
function animate(time: number) { const list = frames(); if (state.playing && list.length && time - state.tick > 1000 / spec().fps) { const next = state.frame + 1; if (next >= list.length && !spec().loop) state.playing = false; else state.frame = next % list.length; state.tick = time; renderTimeline(); renderPreview(); } requestAnimationFrame(animate); }

$('#mediaInput').addEventListener('change', e => { const files = (e.target as HTMLInputElement).files; if (files?.length) importMedia(files).catch(err => alert(err.message)); });
$('#visualStart').addEventListener('change', updateIds); $('#importClip').addEventListener('change', e => selectClip((e.target as HTMLSelectElement).value as ClipId)); $('#tolerance').addEventListener('input', e => $('#toleranceOut').textContent = (e.target as HTMLInputElement).value);
function updateSliceNumber() { const r = editableRegions()[state.selectedSlice], source = state.source; if (!r || !source || r.locked) return; r.x = Number(($('#sliceX') as HTMLInputElement).value) / source.width; r.y = Number(($('#sliceY') as HTMLInputElement).value) / source.height; r.w = Number(($('#sliceW') as HTMLInputElement).value) / source.width; r.h = Number(($('#sliceH') as HTMLInputElement).value) / source.height; normalizeRegion(r); renderSliceStatus(); renderPreview(); }
['sliceX', 'sliceY', 'sliceW', 'sliceH'].forEach(id => $(`#${id}`).addEventListener('change', updateSliceNumber));
$('#canvasPreset').addEventListener('change', e => { const value = (e.target as HTMLSelectElement).value; if (value !== 'custom') { const [w, h] = value.split('x'); ($('#frameWidth') as HTMLInputElement).value = w; ($('#frameHeight') as HTMLInputElement).value = h; slots.forEach(rebuildSlot); renderAll(); } });
function canvasSizeChanged() { ($('#canvasPreset') as HTMLSelectElement).value = 'custom'; slots.forEach(rebuildSlot); renderAll(); }
$('#frameWidth').addEventListener('change', canvasSizeChanged); $('#frameHeight').addEventListener('change', canvasSizeChanged);
$('#establishBaseline').onclick = () => { const f = frames()[state.frame]; if (!f) return alert('先导入并选中一个参考动作帧。'); const b = findBounds(f.raw.getContext('2d')!.getImageData(0, 0, f.raw.width, f.raw.height)); if (!b) return alert('当前帧没有可见角色。'); slot().config.canonicalScale = Math.min((size().h - 12) / b.height, (size().w - 8) / b.width); slot().config.referenceAction = state.clip; slot().clipConfig[state.clip].sourcePivot = { x: b.x + b.width / 2, y: b.y + b.height }; rebuildSlot(); renderAll(); };
$('#canonicalScale').addEventListener('change', e => { slot().config.canonicalScale = Math.max(0.001, Number((e.target as HTMLInputElement).value)); rebuildSlot(); renderAll(); });
function updatePivot() { slot().config.standingPivot = { x: Number(($('#standX') as HTMLInputElement).value), y: Number(($('#standY') as HTMLInputElement).value) }; slot().config.seatPivot = { x: Number(($('#seatX') as HTMLInputElement).value), y: Number(($('#seatY') as HTMLInputElement).value) }; rebuildSlot(); renderAll(); }
['standX', 'standY', 'seatX', 'seatY'].forEach(id => $(`#${id}`).addEventListener('change', updatePivot));
$('#referenceAction').addEventListener('change', e => { slot().config.referenceAction = (e.target as HTMLSelectElement).value as ClipId; renderPreview(); });
function updateClipOffset() { clipConfig().offset = { x: Number(($('#clipOffsetX') as HTMLInputElement).value), y: Number(($('#clipOffsetY') as HTMLInputElement).value) }; frames().forEach(f => rebuildFrame(slot(), state.clip, f)); renderAll(); }
['clipOffsetX', 'clipOffsetY'].forEach(id => $(`#${id}`).addEventListener('change', updateClipOffset));
function updateFrameOffset() { const f = frames()[state.frame]; if (!f) return; f.frameOffset = { x: Number(($('#frameOffsetX') as HTMLInputElement).value), y: Number(($('#frameOffsetY') as HTMLInputElement).value) }; rebuildFrame(slot(), state.clip, f); renderAll(); }
['frameOffsetX', 'frameOffsetY'].forEach(id => $(`#${id}`).addEventListener('change', updateFrameOffset));
$('#onion').addEventListener('change', e => { state.onion = (e.target as HTMLInputElement).checked; renderPreview(); }); $('#onionOpacity').addEventListener('input', e => { state.onionOpacity = Number((e.target as HTMLInputElement).value); renderPreview(); });
$('#showBounds').addEventListener('change', e => { state.showBounds = (e.target as HTMLInputElement).checked; renderPreview(); }); $('#showAnchor').addEventListener('change', e => { state.showAnchor = (e.target as HTMLInputElement).checked; renderPreview(); }); $('#fps').addEventListener('change', e => { spec().fps = Math.max(1, Math.min(30, Number((e.target as HTMLInputElement).value))); renderDetails(); });
$('#play').onclick = () => { state.playing = !state.playing; $('#play').textContent = state.playing ? '❚❚ 暂停' : '▶ 播放'; }; $('#prev').onclick = () => { if (frames().length) { state.frame = (state.frame - 1 + frames().length) % frames().length; syncAlignmentControls(); renderTimeline(); renderPreview(); } }; $('#next').onclick = () => { if (frames().length) { state.frame = (state.frame + 1) % frames().length; syncAlignmentControls(); renderTimeline(); renderPreview(); } };
$('#deleteFrame').onclick = () => { if (frames().length) { frames().splice(state.frame, 1); state.frame = Math.max(0, Math.min(state.frame, frames().length - 1)); renderAll(); } }; $('#duplicateFrame').onclick = () => { const f = frames()[state.frame]; if (f) { const raw = document.createElement('canvas'); raw.width = f.raw.width; raw.height = f.raw.height; raw.getContext('2d')!.drawImage(f.raw, 0, 0); const copy = { ...f, raw, canvas: document.createElement('canvas'), frameOffset: { ...f.frameOffset }, sliceRect: { ...f.sliceRect } }; rebuildFrame(slot(), state.clip, copy); frames().splice(state.frame + 1, 0, copy); state.frame++; renderAll(); } }; $('#flipFrame').onclick = () => { const f = frames()[state.frame]; if (f) { f.raw = flip(f.raw); rebuildFrame(slot(), state.clip, f); renderAll(); } }; $('#sampleFrames').onclick = recommendedSample;
$('#mirrorRight').onclick = () => { const s = slot(); if (!s.clips.walk_left.length) return alert('当前 Slot 没有 Walk Left'); if (s.clips.walk_right.length && !confirm('覆盖已有 Walk Right？')) return; const leftPivot = s.clipConfig.walk_left.sourcePivot; s.clipConfig.walk_right = { offset: { ...s.clipConfig.walk_left.offset }, sourcePivot: leftPivot ? { x: s.clips.walk_left[0].raw.width - leftPivot.x, y: leftPivot.y } : null }; s.clips.walk_right = s.clips.walk_left.map(f => { const mirrored: Frame = { ...f, raw: flip(f.raw), canvas: document.createElement('canvas'), frameOffset: { x: -f.frameOffset.x, y: f.frameOffset.y }, sliceRect: { ...f.sliceRect } }; rebuildFrame(s, 'walk_right', mirrored); return mirrored; }); selectClip('walk_right'); };
$('#saveBatch').onclick = saveBatch; $('#exportBatch').onclick = () => exportBatch().catch(err => alert(err.message)); $('#newBatch').onclick = reset; $('#openBatch').addEventListener('change', e => { const f = (e.target as HTMLInputElement).files?.[0]; if (f) { clearRawFrames(); openBatch(f).catch(err => alert(err.message)); } }); $('#saveLayout').onclick = saveLayout; $('#loadLayout').addEventListener('change', e => { const f = (e.target as HTMLInputElement).files?.[0]; if (f) loadLayout(f).catch(err => alert(err.message)); }); $('#styleGuide').onclick = () => ($('#styleDialog') as HTMLDialogElement).showModal();
$('#applySlices').onclick = applySlicesToCurrentAction;
$('#resetGrid').onclick = () => { const fresh = gridRegions(); if (state.actionOverrides[state.clip]) state.actionOverrides[state.clip] = fresh; else state.baseRegions = fresh; state.selectedSlice = 0; renderAll(); };
$('#createOverride').onclick = () => { state.actionOverrides[state.clip] = cloneRegions(state.baseRegions); state.selectedSlice = Math.min(state.selectedSlice, SLOT_COUNT - 1); renderAll(); };
$('#clearOverride').onclick = () => { delete state.actionOverrides[state.clip]; state.selectedSlice = Math.min(state.selectedSlice, state.baseRegions.length - 1); renderAll(); };
$('#toggleLock').onclick = () => { const item = editableRegions()[state.selectedSlice]; if (item) { item.locked = !item.locked; renderAll(); } };
$('#deleteSlice').onclick = () => { const items = editableRegions(), item = items[state.selectedSlice]; if (!item || item.locked) return; items.splice(state.selectedSlice, 1); renumberRegions(items); state.selectedSlice = Math.max(0, Math.min(state.selectedSlice, items.length - 1)); state.slot = state.selectedSlice; renderAll(); };
$('#addSlice').onclick = () => { const items = editableRegions(); if (items.length >= SLOT_COUNT) return alert('当前已经有 18 个切片。先删除一个，再创建新切片。'); items.push({ id: `character_${String(items.length + 1).padStart(2, '0')}`, x: .35, y: .35, w: .3, h: .3, locked: false }); state.selectedSlice = items.length - 1; state.slot = state.selectedSlice; state.view = 'batch'; setViewButtons(); renderAll(); };
document.querySelectorAll<HTMLElement>('[data-view]').forEach(el => el.onclick = () => { state.view = el.dataset.view as 'batch' | 'character'; setViewButtons(); renderPreview(); }); document.querySelectorAll<HTMLElement>('[data-bg]').forEach(el => el.onclick = () => { const bg = el.dataset.bg!; $('#stage').className = `stage ${bg === 'checker' ? '' : bg}`; });
preview.addEventListener('pointerdown', beginSliceInteraction); preview.addEventListener('pointermove', updateSliceInteraction); preview.addEventListener('pointerup', endSliceInteraction); preview.addEventListener('pointercancel', endSliceInteraction);

updateIds(); renderAll(); requestAnimationFrame(animate);
