import JSZip from 'jszip';
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s);
const nativeCreate=URL.createObjectURL.bind(URL),nativeRevoke=URL.revokeObjectURL.bind(URL),nativeClick=HTMLAnchorElement.prototype.click;
const blobs=new Map<string,Blob>();let capture=false,bypass=false;
URL.createObjectURL=((v:Blob|MediaSource)=>{const u=nativeCreate(v);if(v instanceof Blob)blobs.set(u,v);return u;}) as typeof URL.createObjectURL;
URL.revokeObjectURL=((u:string)=>{blobs.delete(u);nativeRevoke(u);}) as typeof URL.revokeObjectURL;
function real(blob:Blob,name:string){const a=document.createElement('a'),u=nativeCreate(blob);a.href=u;a.download=name;bypass=true;nativeClick.call(a);bypass=false;setTimeout(()=>nativeRevoke(u),1500);}
function waitProjectJson(){return new Promise<{blob:Blob;name:string}>((ok,no)=>{capture=true;const t=setTimeout(()=>{capture=false;no(new Error('保存批次超时'));},60000);const handler=(e:CustomEvent<{blob:Blob;name:string}>)=>{clearTimeout(t);window.removeEventListener('sprite-project-captured',handler as EventListener);ok(e.detail);};window.addEventListener('sprite-project-captured',handler as EventListener);});}
HTMLAnchorElement.prototype.click=function(){if(!bypass&&capture&&this.download.endsWith('.sprite-batch.json')){const blob=blobs.get(this.href);capture=false;if(blob){window.dispatchEvent(new CustomEvent('sprite-project-captured',{detail:{blob,name:this.download}}));return;}}return nativeClick.call(this);};
async function save(){const button=$('#saveProjectZip') as HTMLButtonElement|null;if(button){button.disabled=true;button.textContent='打包工程…';}try{const p=waitProjectJson();($('#saveBatch') as HTMLButtonElement|null)?.click();const captured=await p;const zip=new JSZip();zip.file('project.sprite-batch.json',captured.blob);zip.file('manifest.json',JSON.stringify({schemaVersion:2,createdAt:new Date().toISOString(),projectFile:'project.sprite-batch.json',note:'完整处理状态保存在 project.sprite-batch.json；重新打开后可继续对齐、修边和导出。'},null,2));zip.file('README.txt','造游社员工像素动画工厂工程包\nproject.sprite-batch.json：完整批次状态、切片、动作、手工删除Mask、缩放与参考设置。\n注意：浏览器批次 JSON 已包含当前已处理帧；若需要从完整原视频重新拆帧，请保留外部原视频。\n');const out=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});const id=(($('#batchId') as HTMLInputElement|null)?.value||'batch_001').trim()||'batch_001';real(out,`${id}.spriteproj.zip`);}finally{if(button){button.disabled=false;button.textContent='保存工程 ZIP';}}}
async function open(file:File){const zip=await JSZip.loadAsync(file),entry=zip.file('project.sprite-batch.json');if(!entry)throw new Error('工程包缺少 project.sprite-batch.json');const text=await entry.async('text'),batch=new File([text],'restored.sprite-batch.json',{type:'application/json'}),input=$('#openBatch') as HTMLInputElement|null;if(!input)throw new Error('找不到打开批次入口');const dt=new DataTransfer();dt.items.add(batch);input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));}
function install(){const old=$('#saveProjectZip') as HTMLButtonElement|null;if(!old)return requestAnimationFrame(install);const clone=old.cloneNode(true) as HTMLButtonElement;old.replaceWith(clone);clone.addEventListener('click',()=>void save().catch(e=>alert(`保存工程失败：${e instanceof Error?e.message:String(e)}`)));if(!$('#openProjectFull')){const label=document.createElement('label');label.className='btn ghost';label.innerHTML='打开工程 ZIP<input hidden id="openProjectFull" type="file" accept=".zip,.spriteproj.zip,application/zip">';clone.after(label);$('#openProjectFull')?.addEventListener('change',e=>{const f=(e.target as HTMLInputElement).files?.[0];if(f)void open(f).catch(err=>alert(`打开工程失败：${err instanceof Error?err.message:String(err)}`));});}}
install();
