type Gesture =
  | { kind: 'connected'; x: number; y: number; tolerance: string }
  | { kind: 'eraser'; points: { x: number; y: number }[]; size: string }
  | { kind: 'magic'; clicks: { x: number; y: number; tolerance: string; connected: boolean; mode: string }[] };
type History = { done: Gesture[]; undone: Gesture[] };
const $ = <T extends HTMLElement = HTMLElement>(selector: string) => document.querySelector<T>(selector);
const histories = new Map<string, History>();
let replaying = false;
let eraserStroke: Extract<Gesture, { kind: 'eraser' }> | null = null;
let magicClicks: Extract<Gesture, { kind: 'magic' }>['clicks'] = [];
const frame = () => new Promise(requestAnimationFrame);

function action() { return (($('#importClip') as HTMLSelectElement | null)?.value || 'idle'); }
function slot() { return Number($('.slot-chip.active')?.getAttribute('data-slot') || 0); }
function frameIndex() { const items=Array.from(document.querySelectorAll<HTMLElement>('#timelineStrip .thumb')); return Math.max(0,items.findIndex(x=>x.classList.contains('active'))); }
function key() { return `${slot()}:${action()}:${frameIndex()}`; }
function history(k=key()) { const h=histories.get(k); if(h)return h; const n={done:[],undone:[]} as History; histories.set(k,n); return n; }
function tool(name:string) { return Boolean(document.querySelector(`[data-manual-tool="${name}"].active-view`)); }
function ensureTool(name:string) { if(!tool(name)) document.querySelector<HTMLButtonElement>(`[data-manual-tool="${name}"]`)?.click(); }
function point(e:PointerEvent) { const p=$('#preview') as HTMLCanvasElement|null;if(!p)return null;const r=p.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}; }
function client(p:{x:number;y:number}) { const c=$('#preview') as HTMLCanvasElement|null;if(!c)return null;const r=c.getBoundingClientRect();return {x:r.left+p.x*r.width,y:r.top+p.y*r.height}; }
function dispatch(type:string,p:{x:number;y:number},id=777) { const c=$('#preview') as HTMLCanvasElement|null, q=client(p);if(!c||!q)return;c.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,clientX:q.x,clientY:q.y,pointerId:id,pointerType:'mouse',button:0,buttons:type==='pointerup'?0:1})); }
function push(g:Gesture) { if(replaying)return;const h=history();h.done.push(g);if(h.done.length>30)h.done.shift();h.undone.length=0;sync(); }
function sync() { const h=history(),u=$('#manualUndo') as HTMLButtonElement|null,r=$('#manualRedo') as HTMLButtonElement|null;if(u)u.disabled=!h.done.length;if(r)r.disabled=!h.undone.length; }
async function switchTo(k:string) { const [s,a,f]=k.split(':');document.querySelector<HTMLElement>(`[data-slot="${s}"]`)?.click();await frame();document.querySelector<HTMLElement>(`[data-action="${a}"]`)?.click();await frame();Array.from(document.querySelectorAll<HTMLElement>('#timelineStrip .thumb'))[Number(f)]?.click();await frame(); }
async function play(g:Gesture) { if(g.kind==='connected'){ensureTool('connected-delete');const t=$('#manualTolerance') as HTMLInputElement|null;if(t)t.value=g.tolerance;dispatch('pointerdown',g);dispatch('pointerup',g);return;}if(g.kind==='eraser'){ensureTool('eraser');const s=$('#eraserSize') as HTMLSelectElement|null;if(s)s.value=g.size;g.points.forEach((p,i)=>dispatch(i===0?'pointerdown':'pointermove',p));if(g.points.length)dispatch('pointerup',g.points[g.points.length-1]);return;}ensureTool('magic-wand');for(const c of g.clicks){const t=$('#manualTolerance') as HTMLInputElement|null,connected=$('#magicConnected') as HTMLInputElement|null,mode=$('#magicMode') as HTMLSelectElement|null;if(t)t.value=c.tolerance;if(connected)connected.checked=c.connected;if(mode)mode.value=c.mode;dispatch('pointerdown',c);dispatch('pointerup',c);}$('#deleteMagicSelection')?.click(); }
async function rebuild(k:string) { replaying=true;try{await switchTo(k);$('#resetManualCleanup')?.click();await frame();for(const g of history(k).done){await play(g);await frame();}}finally{replaying=false;magicClicks=[];sync();} }
async function undo(){const k=key(),h=history(k),g=h.done.pop();if(!g)return;h.undone.push(g);await rebuild(k);}
async function redo(){const k=key(),h=history(k),g=h.undone.pop();if(!g)return;h.done.push(g);await rebuild(k);}
function install(){const preview=$('#preview') as HTMLCanvasElement|null,box=$('.manual-cleanup-controls');if(!preview||!box)return requestAnimationFrame(install);if($('#manualUndo'))return;const row=document.createElement('div');row.className='row manual-history-row';row.innerHTML='<button class="btn small" id="manualUndo">↶ 撤销精修</button><button class="btn small" id="manualRedo">↷ 重做精修</button>';box.prepend(row);$('#manualUndo')?.addEventListener('click',()=>void undo());$('#manualRedo')?.addEventListener('click',()=>void redo());preview.addEventListener('pointerdown',e=>{if(replaying)return;const p=point(e);if(!p)return;if(tool('connected-delete'))push({kind:'connected',...p,tolerance:($('#manualTolerance') as HTMLInputElement|null)?.value||'24'});else if(tool('magic-wand'))magicClicks.push({...p,tolerance:($('#manualTolerance') as HTMLInputElement|null)?.value||'24',connected:Boolean(($('#magicConnected') as HTMLInputElement|null)?.checked),mode:($('#magicMode') as HTMLSelectElement|null)?.value||'replace'});else if(tool('eraser'))eraserStroke={kind:'eraser',points:[p],size:($('#eraserSize') as HTMLSelectElement|null)?.value||'1'};},true);preview.addEventListener('pointermove',e=>{if(replaying||!eraserStroke)return;const p=point(e);if(p)eraserStroke.points.push(p);},true);preview.addEventListener('pointerup',()=>{if(replaying||!eraserStroke)return;eraserStroke.points=eraserStroke.points.filter((_,i)=>i===0||i%2===0);push(eraserStroke);eraserStroke=null;},true);$('#deleteMagicSelection')?.addEventListener('click',()=>{if(replaying||!magicClicks.length)return;push({kind:'magic',clicks:magicClicks.map(x=>({...x}))});magicClicks=[];},true);$('#clearMagicSelection')?.addEventListener('click',()=>{if(!replaying)magicClicks=[];},true);$('#resetManualCleanup')?.addEventListener('click',()=>{if(replaying)return;histories.delete(key());magicClicks=[];sync();},true);document.addEventListener('click',e=>{if((e.target as HTMLElement).closest('[data-slot],[data-action],.thumb'))setTimeout(sync,0);});document.addEventListener('keydown',e=>{if((e.target as HTMLElement)?.matches('input,textarea,select'))return;if((e.ctrlKey||e.metaKey)&&!e.shiftKey&&e.key.toLowerCase()==='z'){e.preventDefault();void undo();}if((e.ctrlKey||e.metaKey)&&(e.key.toLowerCase()==='y'||(e.shiftKey&&e.key.toLowerCase()==='z'))){e.preventDefault();void redo();}});sync();}
install();
